version: '3'
services:
  postgresql:
    image: hpsoftware/aos-postgres
    ports:
    - "${POSTGRES_PORT}:5432"
    container_name: postgresql
    restart: always
  tomcat_6:
    env_file:
    - .env
    image: tomcat_all_compose
    ports:
    - "${WARS_PORT}:8080"
    depends_on:
    - "postgresql"
    container_name: tomcat_6
    restart: always
  tomcat_account:
    env_file:
    - .env
    image: tomcat_account_compose
    ports:
    - "${ACCOUNT_PORT}:8080"
    depends_on:
    - "postgresql"
    container_name: tomcat_account
    restart: always

