version: "3.0"
services:
  gitlab:
   env_file:
   - .env
   - .env_private
   image: advantageonlineshopping/aos-gitlab
   ports:
   - "GITLAB_PORT:5432"
   - "443:443"
   - "22:22"
   volumes:
   - '/srv/gitlab/config:/etc/gitlab'
   - '/srv/gitlab/logs:/var/log/gitlab'
   - '/srv/gitlab/data:/var/opt/gitlab'
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  postgresql:
   image: advantageonlineshopping/aos-postgres
   ports:
   - "POSTGRES_PORT:5432"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  tomcat_6:
   env_file:
   - .env
   - .env_private
   image: advantageonlineshopping/aos-main-app
   ports:
   - "MAIN_PORT:8080"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  tomcat_accountservice:
   env_file:
   - .env
   - .env_private
   image: advantageonlineshopping/aos-accountservice
   ports:
   - "ACCOUNT_PORT:8080"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  registry:
   image: registry:2
   ports:
   - "REGISTRY_PORT:5000"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  jenkins:
   env_file:
   - .env
   - .env_private
   image: advantageonlineshopping/aos-jenkins-pipline
   ports:
   - "JENKINS_PORT:8080"
   - "50000:50000"
   volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
