version: '3.0'
services:
  gitlab:
   env_file:
   - .env
   - .env_private
   image: performancetesting/aos-gitlab
   ports:
   - "${GITLAB_PORT}:80"
   - "443:443"
   - "22:22"
   volumes:
   - '/srv/gitlab/config:/etc/gitlab'
   - '/srv/gitlab/logs:/var/log/gitlab'
   - '/srv/gitlab/data:/var/opt/gitlab'
   container_name: gitlab
   restart: always
  postgresql:
    image: performancetesting/aos-postgres
    ports:
    - "${POSTGRES_PORT}:5432"
    container_name: postgresql
    restart: always
  tomcat_6:
    env_file:
    - .env
    - .env_private
    image: performancetesting/aos-main-app
    ports:
    - "${MAIN_PORT}:8080"
    depends_on:
    - "postgresql"
    container_name: tomcat_6
    restart: always
  tomcat_account:
    env_file:
    - .env
    - .env_private
    image: performancetesting/aos-accountservice
    ports:
    - "${ACCOUNT_PORT}:8080"
    depends_on:
    - "postgresql"
    container_name: tomcat_account
    restart: always
  jenkins:
    env_file:
    - .env
    - .env_private
    image: performancetesting/aos-jenkins-pipline
    ports:
    - "50000:50000"
    - "${JENKINS_PORT}:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    restart: always