version: "3.0"
services:
  postgresql:
   image: performancetesting/aos-postgres
   ports:
   - "POSTGRES_PORT:5432"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  tomcat_6:
   env_file:
   - .env
   image: performancetesting/aos-main-app
   ports:
   - "MAIN_PORT:8080"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  tomcat_accountservice:
   env_file:
   - .env
   image: performancetesting/aos-accountservice
   ports:
   - "ACCOUNT_PORT:8080"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME